# Generated by Django 5.1.2 on 2024-10-10 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pyme',
            fields=[
                ('id_PYME', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('categoria', models.CharField(max_length=20)),
                ('descripcion', models.TextField(max_length=500)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('run', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('dv_run', models.CharField(max_length=1)),
                ('p_nombre', models.CharField(max_length=20)),
                ('s_nombre', models.CharField(max_length=20)),
                ('ap_paterno', models.CharField(max_length=20)),
                ('ap_materno', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=50)),
                ('contraseña', models.CharField(max_length=20)),
                ('moderador', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('pyme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pyme')),
            ],
        ),
        migrations.CreateModel(
            name='Resenna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.PositiveSmallIntegerField()),
                ('comentario', models.CharField(blank=True, max_length=500, null=True)),
                ('pyme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pyme')),
            ],
        ),
        migrations.AddField(
            model_name='pyme',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usuario'),
        ),
    ]
