# Generated by Django 5.1.2 on 2024-10-14 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_remove_pyme_usuario_remove_resenna_pyme_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PYME',
            fields=[
                ('id_PYME', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('categoria', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=500)),
                ('estado', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='REPORTE',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('pyme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pyme')),
            ],
        ),
        migrations.CreateModel(
            name='RESENNA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField()),
                ('comentario', models.CharField(blank=True, max_length=500, null=True)),
                ('pyme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pyme')),
            ],
        ),
    ]
