# Generated by Django 5.1.2 on 2024-11-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_grupo2_usergrupo_delete_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyme',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='pymes/'),
        ),
    ]
